from app.dependencies import auth, models
from fastapi import APIRouter, Depends

router = APIRouter(prefix="/users", tags=["users"])


@router.post("", response_model=models.UserOut)
async def create_user(user_in: models.UserIn):
    hashed_password = auth.get_password_hash(user_in.password)
    # UID generated by DB
    user_in_db = models.UserInDB(**user_in.dict(), hashed_password=hashed_password, uid=0)
    print("Saved user!")
    return user_in_db


@router.get("/me")
async def read_current_user(current_user: models.UserInDB = Depends(auth.get_current_user)):
    return current_user
